Libcs50 cpp a petelin
cs50/lib50-cpp pull request #1
Opened 2016-10-04 19:23 UTC by AndrejPetelin

- added check for badbit set in cin in get_string, theoretically it's an unrecoverable error, so throwing runtime_error
- implemented get_char
- implemented get_int
- implemented get_long_long

2016-10-05 15:23 UTC, dmalan requested changes

2016-10-05 15:23 UTC, dmalan commented on src/cs50.cpp
> +        std::cerr << e.what() << std::endl;
Let's not have library have side effects.

2016-10-05 15:23 UTC, dmalan commented on src/cs50.cpp
> +        std::cout << "Retry: ";
Can we somehow force unbuffered `cout` and `cerr`, not just here but anytime library is linked in, a la https://github.com/cs50/lib50-c/blob/master/src/cs50.c#L469?

2016-10-05 15:23 UTC, dmalan commented on src/cs50.cpp
> +                ;
Is there a cleaner way? Can we suppress `stoi`'s (and related functions') potential to throw an exception, checking for an error some other way?

2016-10-05 15:23 UTC, dmalan commented on src/cs50.cpp
> +        std::cerr << "cs50 get_string error: cannot read input!\n";
No need for side effects.

2016-10-05 15:23 UTC, dmalan commented on src/cs50.cpp
> +        throw e;
Is there some sentinel value we could return other than `""` to avoid introducing exceptions?

2016-10-05 15:27 UTC, dmalan commented
See https://github.com/cs50/lib50-cpp/issues/2 regarding `regex`.

2016-10-05 15:29 UTC, dmalan commented on src/cs50.cpp
> +
Breaking the abstraction here. `get_char` shouldn't have to check `cin` just because `get_string` uses it. `get_char` shouldn't even need to know that. Better if `get_string` returns some sentinel value or, if need be, throws an exception that `get_char` catches.

2016-10-05 18:56 UTC, AndrejPetelin commented on src/cs50.cpp
> +        throw e;
Hmmm, I'm open to ideas... perhaps something like a series of '\0' chars or something? Feels a bit hacky to me, but it could be done.

2016-10-06 07:11 UTC, AndrejPetelin commented on src/cs50.cpp
> +                ;
stoi and relatives are C++11 anyway, I'll just change to using a stringstream and pass into a long long to check for max/min.

2016-10-06 22:20 UTC, closed without merging