get_float and get_double added
cs50/lib50-cpp pull request #3
Opened 2016-10-05 06:52 UTC by irenenaya

Doesn't currently work correctly on the IDE because of issues of gcc with regex. According to the gnu documentation, the earliest version that works correctly is 4.9. Just let me know in case there's any issues because of this. Otherwise, I've tested it and works just as the current version of the c get_float() and get_double()
Hope the fork is helpful :)

2016-10-05 15:28 UTC, dmalan commented
Should definitely work in our own IDE. :) See https://github.com/cs50/lib50-cpp/issues/2.

2016-10-05 15:31 UTC, dmalan requested changes

2016-10-05 15:31 UTC, dmalan commented on src/cs50.cpp
> +#include <cfloat>
Stylistically, let's always declare system-wide header files first, alphabetically, then a blank line, then `cs50.h`.

2016-10-05 15:31 UTC, dmalan commented on src/cs50.cpp
> +        }
Same comment as https://github.com/cs50/lib50-cpp/pull/1/files#r82000674.

2016-10-05 15:31 UTC, dmalan commented on src/cs50.cpp
> +        if (std::regex_match(str, re))
See https://github.com/cs50/lib50-cpp/issues/2.

2016-10-05 15:31 UTC, dmalan commented on src/cs50.cpp
> +    }
Superfluous blank line.

2016-10-06 04:21 UTC, irenenaya commented on src/cs50.cpp
> +#include <cfloat>
Fixed, as well as the extra blank lines :)

2016-10-06 04:21 UTC, dmalan requested changes

2016-10-06 04:21 UTC, dmalan commented on src/cs50.cpp
> +        if (str[0] == '\0')
I think we need to give this sentinel some more thought, since we should ideally be able to distinguish between the user just hitting Enter and actual errors. Based on this line, if the user just hit Enter, they wouldn't be re-prompted but should be. Discussing a bit on our end still!

2016-10-06 04:21 UTC, dmalan commented on src/cs50.cpp
> +        if(!isspace(str[0]))
`if (`

2016-10-06 04:21 UTC, dmalan commented on src/cs50.cpp
> +            char* tail;
`char *tail`

2016-10-06 04:21 UTC, dmalan commented on src/cs50.cpp
> +                }
Good approach for compatibility with C library.

2016-10-06 04:21 UTC, dmalan commented on src/cs50.cpp
> +            char* tail;
`char *tail`

2016-10-06 04:21 UTC, dmalan commented on src/cs50.h
> +/** Creates a class in which the constructor cancels buffering for cout.
```
/**
 * Creates
```

2016-10-06 04:21 UTC, dmalan commented on src/cs50.h
> +	public:
Do use 4 spaces throughout, not tabs.

2016-10-06 04:21 UTC, dmalan commented on src/cs50.h
> +
Interesting approach. Just read http://stackoverflow.com/a/10897576 which seems on point. Does `clang++` (or `g++`) support an `__attribute__` that we could use in this C++ library, just like the C library perhaps?

2016-10-06 04:22 UTC, irenenaya commented on src/cs50.cpp
> +        }
Fixed. For now, I put a check for the first character being '\0' , because it was the workaround that Andrej suggested as a reply to one of your comments. Will change according to what get_string() returns in case of error

2016-10-06 04:24 UTC, irenenaya commented on src/cs50.cpp
> +        if (std::regex_match(str, re))
Fixed. Used a modified version of your implementation in the .c library because it seemed the cleanest way. Removed isfinite() because that one is only compatible with the c++11 standard

2016-10-06 04:26 UTC, irenenaya commented on src/cs50.cpp
> +        if (str[0] == '\0')
Yes, that was an oversight on my part. Thanks for pointing it out, I'll add a check for length :)

2016-10-06 04:31 UTC, dmalan commented on src/cs50.cpp
> +        if (str[0] == '\0')
Actually, checking for length won't really help, since the length of `str` will just be 0 in this case. Problem is that we can't have `get_string` return `NULL` as a sentinel value for errors, since it's designed atm to return a `std::string`, which isn't a pointer. So we either need to let `get_string` throw an exception in cases of error or just decide to return `""` in cases of error, equivalent to user just hitting Enter, or ... other ideas welcome! @crossroads1112?

2016-10-06 04:39 UTC, irenenaya commented on src/cs50.h
> +
They actually do. I looked around a lot and in general the agreement seems to be that a static object is more portable (because it's not a GNU extension but a standard feature). __attribute__ works fine in my mac, for example, and I honestly can't find much complaints of it not working in some environments, so I don't mind changing it. I did compile my version as a dynamic library and it works fine, but if you prefer to use __attribute__ I can change it.
Just out of curiosity, why are we unbuffering stdout? :)

2016-10-06 04:55 UTC, dmalan commented on src/cs50.h
> +
Ah, quite true. I shall ponder!

Invariably, buffered stdout leads to confusion when students are debugging, since they'll insert a call to, e.g., `printf` but never see anything printing (e.g., because of an infinite loop) and thus assume execution isn't even reaching the `printf` line, even though it might be!

2016-10-06 05:21 UTC, AndrejPetelin commented on src/cs50.cpp
> +            char* tail;
This is new :) How come, if I may ask?

2016-10-06 05:28 UTC, dmalan commented on src/cs50.cpp
> +            char* tail;
We hypothesized a few years ago that bucking convention and attaching the `*` to the type would be pedagogically clearer, but we haven't any data that it actually is, so in revamping things this fall, we reverted to the more conventional!

2016-10-06 05:38 UTC, AndrejPetelin commented on src/cs50.cpp
> +        if (str[0] == '\0')
won't the length of str be 1 if we do something like str.push_back('\0'); ?

2016-10-06 05:42 UTC, dmalan commented on src/cs50.cpp
> +        if (str[0] == '\0')
Oh I see, you're proposing "\0" as the sentinel. This feels a bit messy, tbh. Not sure we should get students in the habit of checking for a value of our own design.

2016-10-06 05:51 UTC, AndrejPetelin commented on src/cs50.cpp
> +        if (str[0] == '\0')
Yes, a string with '\0' as sentinel. And I agree it feels messy, I'd love to hear your thoughts on it. The only alternative I can come up with is throwing an exception (which I'd actually prefer).

2016-10-06 07:34 UTC, AndrejPetelin commented on src/cs50.cpp
> +        if (str[0] == '\0')
An alternative would be wrapping the string into a class, we can add sentinels (or rather aptly named bool-based accessor functions) at will then...

2016-10-06 07:42 UTC, AndrejPetelin commented on src/cs50.cpp
> +        if (str[0] == '\0')
Actually, another alternative would be wrapping the string into a class like String50 or even String (not my favorite idea since String and string could cause confusion) where we can add any set of accessors we may need instead of a sentinel value.

2016-10-06 11:38 UTC, AndrejPetelin commented on src/cs50.cpp
> +        if (str[0] == '\0')
Also, just to be clear, I'm not suggesting something like
`return std::string("\0");`
which would literally create a string of length two with str[0] == '\' and str[1] == '0' but rather entering a char of 0 into the string. There's no way a user could enter '\0' via keyboard input.

Another alternative would be EOF, but a string with EOF as its only char is just as hacky, imho.

Perhaps get_string could take a bool pointer argument that would default to NULL, so by calling it as get_string() it'd do the usual (empty string on EOF) while get_int, get_float and the rest would call them with a bool value that they'd then test? Kind of like Qt's QString::toInt(), QString::toDouble(),...

2016-10-06 23:24 UTC, irenenaya commented on src/cs50.h
> +
That's true!! I hadn't thought of that! Thanks for clarifying! :)

2016-10-07 12:37 UTC, dmalan commented
See latest comments at https://github.com/cs50/lib50-cpp/pull/4. Let me loop back to confirm, but we're leaning toward throwing an exception in cases of error instead of returning `""`.

2016-10-12 03:05 UTC, crossroads1112 commented on src/cs50.cpp
> +        if (str[0] == '\0')
@dmalan If only C++ had decent algebraic types, alas. I don't like the idea of defining a wrapper class since I think it would be prudent to get students used to using the standard `std::string`. 

Whether to throw an exception or simply return an empty string depends somewhat on how the course using this library is going to be structured. (Speaking of, the course isn't moving away from C is it?). Will exceptions and how to handle them be covered? If so, when? 

That said, despite my personal bias against exceptions, I think they are the right way to go here. These are unrecoverable errors and really should be treated like failed assertions (Speaking above, for things like failure to allocate memory, should we be using assertions in the C library since students surely aren't expected to recover from an error like that). Thus exceptions do not require the student to terminate the program him/herself if there is some strange error reading from stdin.

For recoverable errors like inputting an out-of-range int, I think a default value should be used so that teaching about exceptions can be delayed until later in the course.

2016-10-12 04:23 UTC, irenenaya commented on src/cs50.cpp
> +        if (str[0] == '\0')
Actually, to be clear, the issue is not unrecoverable errors, which I agree are a special case, and they are not out of range type of errors either, which are already handled in our implementation. 
Our main concern was with EOF (be it from a piped file or by pressing ctrl+d). We cannot check it in the individual functions (get_float, get_int, etc.). We tried that first but Prof. Malan made a very good point that checking for cin.eof() inside those functions would break the abstraction. That's why we then went the route of creating a helper function. But since we're not using that, the only way to handle eof is by throwing an error from get_string. We then are catching the error in get_float, get_int, etc. 
The issue is that if the user reads strings by piping a file or if they decide to enter strings within a loop and stopping with ctrl+d, if the error is not caught by the caller, the program will crash when it shouldn't. 
As a reminder, using ctrl+d to stop input from a loop is exactly what the code in find.c does, and I guess the more curious students would want to use it with strings, etc (i know I did back then). 
Returning an empty string is not really a possibility either in the EOF case, because entering an empty string prompts for "Retry:" in the library functions.
I still think the previous version with the helper function was the cleaner one and avoided the students from having to worry about errors, especially if we consider the library as "training wheels" which will be removed later on. I can understand why it's not the preferred idea though and throwing is the next best option. Any suggestions are welcome :)

2016-10-12 05:09 UTC, crossroads1112 commented on src/cs50.cpp
> +        if (str[0] == '\0')
Ah, I apologize, I had not realized the full scope of the issue. 

This isn't very idiomatic C++ but have you considered setting `errno` on EOF (maybe to EPIPE) and having `get_*` read from it and then reset it?

2016-10-12 10:09 UTC, AndrejPetelin commented on src/cs50.cpp
> +        if (str[0] == '\0')
It's an interesting idea, however wouldn't that just bring C error handling into C++? Also get_string does get called directly, it is not merely a helper function, it does get called directly by students using the library as "training wheels".

2016-10-12 14:14 UTC, crossroads1112 commented on src/cs50.cpp
> +        if (str[0] == '\0')
> wouldn't that just bring C error handling into C++

It depends what you mean by C error handling and whether you think that's inherently a bad thing. There are limited ways to communicate state to the calling function: return value, pointer/reference arguments, exceptions or some sort of global state (in this case, in the form of `errno`). The problems with those first three have been highlighted in this thread.

Errno is far from a perfect error reporting system but it has the benefit of being all-but-invisible to students.

2016-10-12 15:41 UTC, AndrejPetelin commented on src/cs50.cpp
> +        if (str[0] == '\0')
I don't think it's inherently a bad thing, but as you said, it is not exactly idiomatic C++. Introducing globals for error handling is unnecessary here, plus it doesn't really solve the problem of not returning an empty string on EOF.

So instead of having to use a try/catch block the students would have to check for state of errno. If that is the case I don't know if it's not a better idea to just return a C string from get_string. It will be invisible to students in the same sense as errno, which is not necessarily what should happen. The C version will still crash if you dereference the pointer.

The C++ version with returning a new C string would crash on dereferencing nullptr (or NULL, actually, to maintain C++98 compatibility) as well, but if passing it to std::string constructor/assignment operator it actually gets dereferenced in there. So there's probably no advantage over throwing an error (apart from the ability to check for a null pointer, but that'd be even more involved, you'd need a char\* that would then be copied into the string if not NULL).

2016-10-12 18:15 UTC, AndrejPetelin commented on src/cs50.cpp
> +        if (str[0] == '\0')
So to clarify - the options so far:
- throw error on EOF:
up side is it's idiomatic C++ and it more or less maintains the behavior of the C library.
down side is it's perhaps less intuitive and will crash the program in the absence of a try/catch block on EOF.

- using errno:
up side is it can be invisible to the students and won't crash the program,
down side is the function then returns an empty string which is not what the C library does - the latter will cause a segfault on dereferencing the NULL char pointer.

-using a non-const pointer/reference as argument to string:
up side - can be invisible on students if done like in, for example, the Qt framework's QString toInt, toFloat,... functions.
down side is we're again returning an empty string.

-returning a char* (copied from std::string's c_str function)
up side is we can return a NULL on EOF,
down side - if students do something like `std::string str = get_string();` it will crash upon the constructor/assignment operator call when NULL is returned (in order to actually check the return the student would have to store the return into a char* before actually passing it to the string, plus delete[] would have to be called manually on it.

2016-10-15 23:27 UTC, dmalan commented
Will follow up shortly!

2016-10-16 03:16 UTC, dmalan requested changes

2016-10-16 03:16 UTC, dmalan commented on src/cs50.cpp
> +/**
For consistency with the C library (and for readability's sake for students), best if each of the `get_*` methods call `get_string` rather than this helper function, I'd say!

2016-10-16 03:16 UTC, dmalan commented on src/cs50.cpp
> +            // load string into a stringstream
What's the motivation for the `stringstream` over `strtod`?

2016-10-16 03:16 UTC, dmalan commented on src/cs50.cpp
> +            if (is >> d && is.eof())
How does `>>` behave in cases of leading or trailing whitespace? (We'd want to disallow both.)

2016-10-16 03:18 UTC, dmalan commented on src/cs50.cpp
> +        throw std::domain_error("cs50::get_string: bad input");
Let's only throw `std::runtime_error` in cases of error. In cases of `EOF`, let's just return an empty `std::string`.

2016-10-16 20:58 UTC, irenenaya commented on src/cs50.cpp
> +            if (is >> d && is.eof())
Leading whitespace is checked for at the beginning, in

` if (str.length() > 0 && !isspace(str[0])) `

Trailing whitespace gets taken care in the is.eof() part, which makes sure we're at the end of the stringstream :)

2019-07-29 15:51 UTC, dmalan commented
So sorry for letting this linger so long, @irenenaya! I hope you won't mind we ended up taking a different approach!

2019-07-29 15:51 UTC, closed without merging