implemented get_string, get_int, get_long_long, get_char, centralized…
cs50/lib50-cpp pull request #4
Opened 2016-10-06 23:10 UTC by AndrejPetelin

… error handling via read_input that's not exposed to library users.

2016-10-07 12:15 UTC, dmalan commented on src/cs50.cpp
> +std::string read_input(bool *ok)
Let's avoid defining helper functions. Better if students can read, e.g., `get_string` and follow it top to bottom as a single function, just like the C library. And `get_int` et al. should then call `get_string`.

2016-10-07 12:17 UTC, dmalan commented on src/cs50.cpp
> +        return std::string();
We're leaning toward throwing an exception now, just fyi, as the closest analog of returning `NULL` in C.

2016-10-07 12:57 UTC, AndrejPetelin commented on src/cs50.cpp
> +        return std::string();
even on EOF?

2016-10-07 13:09 UTC, AndrejPetelin commented on src/cs50.cpp
> +std::string read_input(bool *ok)
So to be clear... get_string would throw an exception on, say, EOF, and get_int et. al would catch and handle the exception by returning INT_MAX/LLONG_MAX/CHAR_MAX...?

This would mean that hitting CTRL+D with get_int would return the sentinel value INT_MAX, however it would crash the program in the absence of error handling by the user whenever get_string would get called directly.

I'm sorry for the amount of questions, I'm quite sure I'm missing something here...

2016-10-09 11:42 UTC, AndrejPetelin commented on src/cs50.cpp
> +        return std::string();
Done. I don't know if I agree with throwing exception on illegal input like EOF. Particularly since it means get_string crashes on absence of exception handling from the library user while get_char, get_int and the rest return a sentinel value.

2016-10-09 16:46 UTC, AndrejPetelin commented on src/cs50.cpp
> +        }
std::domain_error seems the best I can find for illegal input.

2016-10-15 23:27 UTC, dmalan commented
Will follow up shortly!

2016-10-16 03:20 UTC, dmalan requested changes

2016-10-16 03:20 UTC, dmalan commented on src/cs50.cpp
> +        catch (const std::domain_error& e)
Not sure we need `domain_error`. `runtime_error` should suffice?

2016-10-16 03:20 UTC, dmalan commented on src/cs50.cpp
> +            if (iss >> ret && iss.eof())
How does `>>` handle an input like `0.0`?

2016-10-16 10:51 UTC, AndrejPetelin commented on src/cs50.cpp
> +            if (iss >> ret && iss.eof())
It reads 0 into ret and leaves ".0" in the stringstream.

2016-10-16 12:38 UTC, AndrejPetelin commented on src/cs50.cpp
> +        catch (const std::domain_error& e)
Right, I picked domain_error as I felt it would be somewhat clearer as to what its intention is particularly in case of EOF. This point is now moot since we're returning an empty `string` on EOF anyway.

Will correct and update today :)

2016-10-16 23:20 UTC, AndrejPetelin commented on src/cs50.h
> +std::string get_string(bool *is_eof = NULL);
@dmalan I'm aware this may feel a bit hacky, but it's probably the simplest way of allowing students to just call `get_string()` without passing an argument while at the same time allowing the `get_int`, `get_char` etc. functions to distinguish between an empty string and `EOF` as input and avoiding introducing a helper function. Would love to read your thoughts on it.

I actually got the idea from Qt framework's QString class that uses this approach to notify library users that functions such as `toInt`, `toDouble`, `toLong` have not succeeded extracting the appropriate value from the QString. 
[http://doc.qt.io/qt-5/qstring.html#toInt](url)

2017-06-14 04:45 UTC, closed without merging