get_string and get_int
cs50/lib50-cpp pull request #6
Opened 2016-10-13 01:04 UTC by IvanJasenov

@dmalan Here is my draft version. I've been trying to keep it as simple as possible due to the pedagogical reasons, just exploited the `string` class and its methods. If you think it'll be better to go with dynamically allocated memory for buffers and with GC, let me know.

2016-10-13 17:24 UTC, AndrejPetelin commented on src/cs50.cpp
> +using namespace std;
I'd say that from an educational point of view it makes sense that standard library types are prepended with std:: in code, not sure that using namespace std; is a good idea from that point of view.

2016-10-13 17:24 UTC, AndrejPetelin commented on src/cs50.cpp
> +		if (isalpha(tmp[i]))
What happens when whitespace or punctuation was entered?

2016-10-13 17:24 UTC, AndrejPetelin commented on src/cs50.cpp
> +			get_int();
Why recursive? Nothing wrong with recursion per se, but aren't there cleaner ways of doing this than mutating a static variable via recursion?

edit: sorry, you're actually not declaring a static string... the static int will get its final assignment on the way back down the recursion so the last value assigned will actually be from the first function call, won't it?

2016-10-13 17:24 UTC, AndrejPetelin commented on src/cs50.cpp
> +	num = stoi(tmp);
stoi is a function that was added to the C++ standard library with the C++11 standard. I think that, as per #2 , the C++98 standard conforming compilers/standard library should be supported?

2016-10-13 17:24 UTC, AndrejPetelin commented on src/cs50.cpp
> +const string get_string(void)
What is the point of returning a const string? IMO there's no point in enforcing constness of strings in a language that does not treat strings as const, not to mention this won't work anyway. Unless you assign the return to a const std::string variable the contents of the return get copied anyway. To my knowledge, the only practical use for returning something like const std::string& (note the return by reference) is to disable the ability of mutating a string that was returned via an accessor function to disallow mutating a string that's a data member of your class via an external reference variable.

2016-10-13 17:24 UTC, AndrejPetelin commented on src/cs50.cpp
> +	if ((tmp.empty() || isspace(tmp[0])) && (tmp.size() != tmp.max_size()))
AFAIK the C library allows entering a string starting with whitespace. It is, however, disallowed in get_int, get_float etc. the check tmp.size() != tmp.max_size() is also probably not what you're looking for. Memory exhaustion in the program can happen way before the theoretical limit of string's size is achieved (std::bad_alloc may be thrown in those cases).

2016-10-13 17:24 UTC, AndrejPetelin commented on src/cs50.cpp
> +		get_string();
This is another recursive call to get_string() that doesn't. Have you tried entering EOF into the string? It will throw a tirade of "please retry!" at you until stack overflow :)

2016-10-13 21:52 UTC, IvanJasenov commented on src/cs50.cpp
> +using namespace std;
Agree with you Andrej, but this is just the initial step of the development. Here I want to see if going with exploiting `string` class is good design solution or I should go with dynamic allocation for the input and do all the "mumbo-jumbo" along the way. Speaking of which, in my workspace I do `#include <bits/stdc++.h>`

2016-10-13 21:56 UTC, IvanJasenov commented on src/cs50.cpp
> +		if (isalpha(tmp[i]))
It'll break for whitespace and alphabet and retry, whitespace checking is done by the `get_string` but will dump if punctuation.
Fine tuning it for the punctuation and EOF is maybe the very last step.

2016-10-13 22:08 UTC, AndrejPetelin commented on src/cs50.cpp
> +		if (isalpha(tmp[i]))
AFAIK whitespace at the beginning should be allowed in get_string but not in get_int. By entering whitespace I meant more like something like "2 3 four"

2016-10-13 22:10 UTC, IvanJasenov commented
Agree on that.

On Oct 14, 2016 00:08, "Andrej Petelin" <notifications@github.com> wrote:

> *@AndrejPetelin* commented on this pull request.
> ------------------------------
>
> In src/cs50.cpp <https://github.com/cs50/lib50-cpp/pull/6>:
>
> > @@ -45,7 +46,20 @@ float get_float(void)
>  int get_int(void)
>  {
>      // TODO
> -    return 0;
> +    static int num;
> +	string tmp = get_string();
> +	// check for correct format
> +	for (int i = 0; i != tmp.size(); ++i)
> +	{
> +		// no need for INT_MAX checking
> +		if (isalpha(tmp[i]))
>
> AFAIK whitespace at the beginning should be allowed in get_string but not
> in get_int. By entering whitespace I meant more like something like "2 3
> four"
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cs50/lib50-cpp/pull/6>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGwQjzUxV9rNoJ3TFXuEL0_OrotJqD5nks5qzqv5gaJpZM4KVYM5>
> .
>

2016-10-13 22:12 UTC, irenenaya commented on src/cs50.cpp
> +		if (isalpha(tmp[i]))
Actually, it won't. If you enter an alpha string, it will keep prompting for a retry as many times as there are characters in the string, even if you enter digits when reprompted. Then, at the end, it will crash because stoi() will always receive the string entered originally and stoi() throws if you give it an input that can't be converted to an int. It will crash also, of course, if you enter any punctuation. 
Also, since get_string() should allow whitespace (there's no reason why it shouldn't) the check for whitespace should be done here, and not in get_string(). Also, get_int() should not allow whitespace in any position, not just at the beginning. If the user intends to enter "234" and by mistake they enter "23 4", they should be prompted to retry, instead of returning 23. 
Also, if the user enters a number that exceeds INT_MAX, the program crashes, which it shouldn't.

2016-10-13 22:13 UTC, IvanJasenov commented on src/cs50.cpp
> +			get_int();
`string tmp = get_string()` creates and object in the memory space when `get_int` is invoked since it uses it as `stdin' "parser". Creates object of type `static string` on each call. Recursion can be easily done with good old iteration, for loop and probably bound to some number of tries but that's the final touch.

2016-10-13 22:16 UTC, IvanJasenov commented on src/cs50.cpp
> +	num = stoi(tmp);
I used the C++11(in Clang) which is deployed by almost all vendors. If needed the C++98 standard for `string` to `int` conversion, it can easily be solved.

2016-10-13 22:23 UTC, IvanJasenov commented on src/cs50.cpp
> +const string get_string(void)
Speaking of why `string` class at the first, I'd rather go with `vector` class and some helper functions along the way but since it's target group is Students who are new to programming I don't want to "complicate" further, so I piggybacked on C conventions. Also I don't know how much I can "press" before raising the "not pedagogical" alert.

2016-10-13 22:28 UTC, IvanJasenov commented on src/cs50.cpp
> +	if ((tmp.empty() || isspace(tmp[0])) && (tmp.size() != tmp.max_size()))
I think this library is not aimed to be the "workhorse". If speaking about memory efficiency and robustness, it's area near and dear to my heart. If needed to be fine tuned, here I am!

2016-10-13 22:30 UTC, IvanJasenov commented on src/cs50.cpp
> +		get_string();
Yes, haven't captured every corner case. As I said, it's just an initial version. By the end of the weekend I hope I'd wrap it up all.

2016-10-13 22:53 UTC, IvanJasenov commented on src/cs50.cpp
> +		if (isalpha(tmp[i]))
Will bound the recursion. Thanx @irenenaya

2016-10-13 23:13 UTC, AndrejPetelin commented on src/cs50.cpp
> +			get_int();
not sure what you mean by "creates object of type static string on each call." See [https://en.wikipedia.org/wiki/Static_variable](url) Note that the static variables local to functions have the same rules in C++ as they do in C, so the example on the Wikipedia entry is relevant here.

Recursion adds function calls to the stack, once the base case is reached the functions are cleared from the stack and the first call to function is actually the last to clear the stack.

2016-10-13 23:29 UTC, irenenaya commented on src/cs50.cpp
> +const string get_string(void)
But according to the C conventions, or rather, the cs50 C library conventions, you shouldn't return a const anyway, should you? From what I can understand, that was what Andrej was asking, not why use an std::string. The two options, btw, is not whether to use a std::string or an std::vector. It seems clear to me from the skeleton code that using a vector was never even thought of (no idea why you would, to be honest). In any case, the choice is between std::string and a C string. I personally think std::string is the way to go in this case. And definitely not returning a const.

2016-10-13 23:33 UTC, AndrejPetelin commented on src/cs50.cpp
> +const string get_string(void)
std::string is standard C++ and is implemented similarly to std::vector. There is generally no need to use a vector in place of a string since both do RAII-style memory management. C conventions have nothing to do with either, it's a simple fact that there are overloaded bitshift operators for std::string and std::iostreams that allow for very easy and intuitive reading and printing of strings. No such overloads for vector<char> exist though.

This isn't about "pedagogical", it's about readability, expressivenes, concisenes and ease of use IMHO.

2016-10-13 23:37 UTC, IvanJasenov commented on src/cs50.cpp
> +			get_int();
My main goal why static was to set the default value to be an empty string. Speaking of the article, my eyes hurt when is see assigning 0 to a static variable.

2016-10-13 23:42 UTC, AndrejPetelin commented on src/cs50.cpp
> +using namespace std;
Generally it's wise to stick to conventions. And using std::string (that, by the way, does all the dynamic memory management for you) is definitely a convention. Manual allocation via new should probably be avoided, but I'm not sure what this has to do with using namespace std;?

2016-10-13 23:46 UTC, AndrejPetelin commented on src/cs50.cpp
> +			get_int();
All C++ standard library containers are initialized as empty by their constructors. Unlike native types, they're not filled with garbage values and you can safely assume that string's size is going to be zero when constructed with the default (no arguments) constructor.

2016-10-13 23:48 UTC, IvanJasenov commented on src/cs50.cpp
> +const string get_string(void)
`const` is simply by preventing its output to be somehow modified along the code or by student/user.
Come on guys, it's just an initial idea of whether I should go with `string` class or C type string, `char*` and keep it as simple as possible and work within the `namespace 50.` The work has just begun.

If showing up skills and Engineering savviness was on the stack...that would be whole another story. :)

2016-10-13 23:50 UTC, IvanJasenov commented on src/cs50.cpp
> +using namespace std;
`cout`lives in std, among others as well.

2016-10-13 23:53 UTC, IvanJasenov commented on src/cs50.cpp
> +			get_int();
`string s{}` I know about it.

2016-10-13 23:58 UTC, irenenaya commented on src/cs50.cpp
> +const string get_string(void)
Just to make sure this is clear: if the students call your function the way they will always do

`std::string name = get_string();`

Then there are 2 options: 1) If the -Wall -Werror flags are set up, then the code will not compile because the compiler will issue a warning about the const-ness being lost, or
2) Without those flags the string 'name' will not be a const string and will be fully modifiable. Anyway, this has already been discussed in the c library and it seems to be that the agreement was not to return a const probably because there is no real reason to avoid modifying a string when the type allows it.

2016-10-13 23:58 UTC, AndrejPetelin commented on src/cs50.cpp
> +			get_int();
std::string s{} is C++11, by the way, but std::string s; will initialize an empty string just the same.

std::string s = "Hello world!"; will initialize it so that s.size(); will return 11.

2016-10-14 00:00 UTC, IvanJasenov commented on src/cs50.cpp
> +const string get_string(void)
@irenenaya I know about the c library, it was my idea going with `const`

2016-10-14 00:16 UTC, irenenaya commented on src/cs50.cpp
> +const string get_string(void)
That's precisely why i was puzzled about seeing you do it here again :)

2016-10-14 00:20 UTC, IvanJasenov commented on src/cs50.cpp
> +const string get_string(void)
...it lurks in the back of my head since! :)

2016-10-15 23:27 UTC, dmalan commented
Will follow up shortly!

2016-10-16 03:39 UTC, dmalan requested changes

2016-10-16 03:39 UTC, dmalan commented on src/cs50.cpp
> +			cout << "please retry!" << endl;
Not consistent with the C library!

2016-10-16 03:39 UTC, dmalan commented on src/cs50.cpp
> +			get_int();
No need to clutter the stack with recursive calls (especially if the compiler might not unwind it as tail-recursive).

2016-10-16 03:39 UTC, dmalan commented on src/cs50.cpp
> +	num = stoi(tmp);
Given that we support C99 for C, C++98 feels better than C++11, lest teachers' environments be pre-C++11.

2016-10-16 03:39 UTC, dmalan commented on src/cs50.cpp
> +const string get_string(void)
Returning `std::string` feels like the closest C++ match to the C library!

2016-10-16 03:39 UTC, dmalan commented on src/cs50.cpp
> +    static string tmp;
Why bother with `static`?

2016-10-16 21:48 UTC, IvanJasenov commented
@dmalan Thanks for the references. Gonna work it over again.

2016-10-16 21:53 UTC, closed without merging